<html>
    <head>
    <title>任务构建结果</title>
    </head>
    <body>
        <p><h2>任务构建结果</h2><input type="button" value="返回主页" onclick="location.href='http://10.132.47.15:4502/home'"></p>
        <p>
            构建流程
        </p>
       	<p>
            1.拉取代码...
        </p>
        <p>
            2.连接sonar，代码静态扫描，给出分析报告...
        </p>
        <p>
            3.单元测试(还没加上)...
        </p>
        <p>
            4.制品构建（基于基础镜像加上代码打包成新的镜像，保存到仓库中）...
        </p>
        <p>
            5.代码发布（通过新的制品镜像启动容器发布服务）
        </p>
        <p><h4>
            {{tjobname}}项目构建结果：{{tresult}}
        </p>
    </body>
</html>